

training_data = [
    {
        "intent": "greet",
        "examples": [
            "salut à toi", "bonjour tout le monde", "hello à tous", "salutations à vous", "salut comment vas-tu",
            "coucou ça va", "salut c'est moi", "bonjour à toi", "bonjour comment vas-tu", "salut comment ça va aujourd'hui",
            "yo comment ça va", "hey tout le monde", "hey salut", "yo bonjour", "salut c'est encore moi",
            "hey comment tu te sens", "rebonjour à toi", "coucou comment ça va", "hello tout le monde",
            "salut tout le monde", "yo salut", "salut je suis de retour", "salut, que fais-tu", "bonjour ça va",
            "salut à nouveau", "salut, tu es là", "salut l'ami", "bonjour à vous", "hello, encore toi", "bonjour, ça fait longtemps",
            "bonjour, comment vas-tu", "salut, tout va bien ?", "hey, comment ça se passe", "salut, tu es là depuis longtemps ?",
            "hello, bien ou bien ?", "hey, quoi de neuf ?", "bonjour, comment se passe ta journée ?", "salutations, comment vas-tu",
            "coucou, ça roule ?", "salut, comment ça va aujourd'hui ?", "bonjour, j'espère que tu vas bien", "hey, tout va bien ?", 
            "yo, comment ça se passe", "salut, tout va comme tu veux ?", "bonjour, comment ça va en ce moment ?", 
            "salut, comment tu te sens aujourd'hui ?", "bonjour, j'espère que tout va bien", "hello, tu vas bien ?", 
            "salutations, quoi de neuf ?", "bonjour, tu es de retour ?", "salut, comment te sens-tu ?", "salut, comment s'est passée ta journée ?",
            "bonjour, que fais-tu aujourd'hui ?", "hello, comment ça va en général ?", "salut, ça se passe bien ?", "salut, tout se passe comme tu veux ?", 
            "bonjour, comment se passe ta semaine ?", "salut, que fais-tu en ce moment ?", "yo, tu es là ?", "salut, quoi de neuf depuis notre dernier échange ?", 
            "bonjour, quoi de prévu aujourd'hui ?", "salut, comment ça roule ?", "bonjour, ça va depuis la dernière fois ?", "salut, bien dormi ?", 
            "hello, que puis-je faire pour toi ?", "bonjour, comment vas-tu depuis ce matin ?", "salut, content de te revoir", "salut, tu vas bien depuis la dernière fois ?", 
            "salut, tu es en forme ?", "bonjour, quoi de prévu pour aujourd'hui ?", "salut, comment puis-je t'aider ?", "salut, quoi de neuf aujourd'hui ?", 
            "bonjour, comment va ta journée ?", "salut, comment ça va depuis notre dernière discussion ?", "salut, quoi de beau ?", 
            "bonjour, tu es là depuis combien de temps ?", "salut, ça faisait longtemps !"
        ],
        "response": "Bonjour, comment puis-je vous aider aujourd'hui ?",
        "next_intent": None
    },
    {
        "intent": "exit",
        "examples": [
            "je m'en vais", 
            "bonne soirée", 
            "je dois te laisser", 
            "on se reparle plus tard", 
            "à plus tard", 
            "je te laisse", 
            "c'était sympa, au revoir", 
            "à la prochaine", 
            "merci, ciao", 
            "je me déconnecte", 
            "je dois partir", 
            "au revoir", 
            "à bientôt", 
            "bye", 
            "je dois y aller", 
            "fin de la conversation", 
            "merci pour tout", 
            "merci, au revoir", 
            "je vais partir maintenant", 
            "je dois m'en aller", 
            "on se voit plus tard", 
            "merci pour ton aide", 
            "ça suffit pour aujourd'hui", 
            "je me retire", 
            "je dois quitter", 
            "merci pour tout, à la prochaine", 
            "je vais m'en aller", 
            "fin de la discussion", 
            "je vais devoir partir", 
            "ça sera tout pour aujourd'hui", 
            "merci, à bientôt"
        ],
        "response": "Au revoir, prenez soin de vous !",
        "next_intent": None
    },
    {
        "intent": "ask_flu_symptoms",
        "examples": [
            "Quels symptômes apparaissent avec la grippe", "Quels sont les premiers signes de la grippe",
            "Comment reconnaître les symptômes de la grippe", "Ai-je les symptômes de la grippe", 
            "Comment savoir si je suis grippé", "Est-ce que mes symptômes correspondent à la grippe", 
            "Comment savoir si j'ai attrapé la grippe", "Quels sont les indicateurs d'une grippe", 
            "Comment se manifestent les symptômes de la grippe", "Quels sont les signes typiques de la grippe", 
            "Comment identifier une grippe", "Est-ce que j'ai les symptômes de la grippe", 
            "Que ressent-on avec la grippe", "Quels sont les symptômes physiques de la grippe", 
            "Quels sont les principaux symptômes de la grippe", "Est-ce que la grippe commence par de la fièvre", 
            "Comment différencier un rhume d'une grippe", "Comment savoir si c'est la grippe ou un rhume", 
            "Fièvre et courbatures, est-ce la grippe", "Quels sont les premiers symptômes ressentis avec la grippe", 
            "Qu'est-ce qui différencie la grippe du rhume", "Est-ce que la grippe donne mal à la gorge", 
            "Quels sont les symptômes respiratoires de la grippe", "Que ressent-on au début d'une grippe", 
            "Comment diagnostiquer la grippe soi-même", "Quels symptômes apparaissent en premier avec la grippe", 
            "Quels sont les signes d'une infection grippale", "Est-ce que la grippe donne toujours de la fièvre", 
            "Comment la grippe affecte-t-elle le corps", "Est-ce que la grippe donne toujours des douleurs musculaires",
            "Est-ce que la grippe donne des maux de tête", "Quels sont les signes avant-coureurs de la grippe", 
            "Est-ce que la grippe provoque des frissons", "Quels sont les symptômes courants de la grippe", 
            "Est-ce que la grippe cause de la fatigue", "Quels sont les symptômes digestifs liés à la grippe", 
            "Comment savoir si j'ai une forte grippe", "La grippe peut-elle causer des douleurs articulaires", 
            "Quels symptômes apparaissent en premier avec une grippe", "Est-ce que la grippe provoque des nausées", 
            "Quels sont les premiers signes de la grippe chez les enfants", "Quels sont les symptômes graves de la grippe", 
            "Combien de temps durent les symptômes de la grippe", "Quels sont les symptômes classiques de la grippe", 
            "Comment savoir si ma grippe est sérieuse", "Comment détecter une grippe dès les premiers signes", 
            "Est-ce que la grippe provoque une toux sèche", "Quels symptômes de la grippe nécessitent une consultation", 
            "Est-ce que la grippe cause des vertiges", "Quels sont les symptômes atypiques de la grippe", 
            "Est-ce que la grippe provoque des douleurs dans la poitrine", "Est-ce que la grippe peut causer une perte de goût ou d'odorat",
            "Comment savoir si la grippe est grave", "Quels sont les signes précoces de la grippe", 
            "Est-ce que la grippe provoque une toux grasse", "Quels sont les symptômes typiques de la grippe", 
            "Comment différencier la grippe des autres virus", "Quels sont les signes cliniques de la grippe", 
            "Est-ce que la grippe affecte les enfants différemment", "Quels sont les symptômes de la grippe chez les adultes", 
            "Quels sont les symptômes de la grippe chez les personnes âgées", "Est-ce que la grippe peut causer des douleurs abdominales", 
            "Comment reconnaître une grippe sévère", "Quels sont les symptômes modérés de la grippe", 
            "Est-ce que la grippe provoque des courbatures sévères", "Est-ce que la grippe donne des frissons sans fièvre", 
            "Quels sont les symptômes de la grippe non accompagnés de fièvre", "Quels sont les signes d'une grippe avancée"
        ],
        "response": "Les symptômes de la grippe incluent la fièvre, la toux, et des douleurs musculaires. Avez-vous de la fièvre ?",
        "next_intent": "ask_flu_fever"
    },
    {
        "intent": "ask_flu_fever",
        "examples": [
            "Est-ce que la grippe cause toujours de la fièvre", "Ma température est élevée, est-ce que j'ai la grippe",  "oui je crois que la fièvre",
            "Fièvre de 38,5°C, est-ce grave", "J'ai de la fièvre depuis ce matin, est-ce la grippe",  
            "Combien de fièvre est normal avec la grippe", "Une forte fièvre est-elle un signe de grippe", 
            "Fièvre élevée, dois-je m'inquiéter", "Est-ce que la grippe donne une fièvre forte", 
            "Est-ce que 38°C est une température normale pour la grippe", "Température qui monte à 40°C, est-ce grave", 
            "J'ai une fièvre de 39,5°C, est-ce lié à la grippe", "Fièvre persistante, est-ce la grippe", 
            "À quel niveau de température dois-je consulter pour la grippe", "La fièvre fait-elle partie des symptômes de la grippe", 
            "Température anormalement élevée, est-ce la grippe", "Comment savoir si la fièvre est causée par la grippe", 
            "Fièvre importante, que faire", "Fièvre modérée, est-ce lié à la grippe", "À partir de quelle température s'inquiéter avec la grippe", 
            "Ma fièvre ne descend pas, est-ce normal pour la grippe", "J'ai une légère fièvre, est-ce un symptôme de grippe", 
            "Combien de jours la fièvre dure-t-elle avec la grippe", "Est-ce que la grippe cause toujours une forte fièvre", 
            "Fièvre constante, dois-je consulter un médecin", "Fièvre de 38,7°C, dois-je m'inquiéter", 
            "Température corporelle élevée, est-ce lié à la grippe", "Est-ce que la grippe cause des pics de température", 
            "Est-ce que la fièvre est le premier symptôme de la grippe", "J'ai de la fièvre et je tousse, est-ce la grippe",
            "J'ai 39°C, est-ce dangereux ?", "La fièvre monte et descend, est-ce normal ?", 
            "Dois-je surveiller ma température de près ?", "Est-ce que la grippe donne une fièvre intermittente ?", 
            "J'ai une température qui fluctue, est-ce inquiétant ?", "Est-ce qu'une fièvre à 38°C est grave avec la grippe ?", 
            "Température de 39°C, dois-je m'inquiéter ?", "Comment faire baisser une fièvre de grippe ?", 
            "Est-ce que la grippe peut causer des frissons avec la fièvre ?", "Comment gérer une température élevée avec la grippe ?", 
            "Mon enfant a de la fièvre avec la grippe, que faire ?", "La fièvre peut-elle être dangereuse avec la grippe ?", 
            "Est-ce que je dois prendre un médicament pour faire baisser la fièvre ?", "À quel moment dois-je appeler un médecin pour la fièvre ?", 
            "Est-ce que la fièvre est toujours présente avec la grippe ?", "Ma fièvre dépasse 39°C, est-ce inquiétant ?", 
            "Dois-je aller à l'hôpital pour une fièvre élevée avec la grippe ?", "Comment savoir si la fièvre est liée à la grippe ou à autre chose ?", 
            "Dois-je surveiller la température toutes les heures ?", "Est-ce qu'une fièvre persistante est dangereuse ?", 
            "À partir de quelle température faut-il s'inquiéter avec la grippe ?", "Dois-je consulter un médecin pour une fièvre de grippe persistante ?", 
            "Est-ce que 38,5°C est normal avec la grippe ?", "Comment traiter une fièvre de grippe ?", 
            "J'ai de la fièvre depuis plusieurs jours, est-ce la grippe ?", "La fièvre a atteint 40°C, dois-je consulter immédiatement ?"
        ],
        "response": "Une température supérieure à 38°C est un symptôme de la grippe. Si elle dépasse 39°C, consultez un médecin.",
        "next_intent": "ask_flu_treatment"
    },
    {
        "intent": "ask_flu_treatment",
        "examples": [
            "Que prendre contre la grippe", "Comment guérir rapidement d'une grippe", "Quels médicaments sont efficaces contre la grippe",
            "Quels remèdes naturels pour la grippe", "Dois-je consulter un médecin pour la grippe", "Comment soulager les symptômes de la grippe",
            "Est-ce que les tisanes aident à soigner la grippe", "Quels traitements sont recommandés pour la grippe", 
            "Comment faire baisser la fièvre due à la grippe", "Dois-je prendre des antibiotiques pour la grippe", 
            "Quels sont les traitements de la grippe à domicile", "Faut-il rester au lit en cas de grippe", 
            "Quel est le meilleur traitement pour la grippe", "Comment traiter la grippe chez les enfants", 
            "Que faire en cas de grippe sévère", "Comment réduire les courbatures liées à la grippe", 
            "Quel remède pour apaiser la toux avec la grippe", "La grippe se soigne-t-elle avec du paracétamol", 
            "Comment diminuer la fatigue avec la grippe", "Dois-je prendre de la vitamine C pour la grippe", 
            "Quel traitement naturel pour combattre la grippe", "Comment se remettre rapidement d'une grippe", 
            "Comment gérer la grippe à la maison", "Quels aliments consommer en cas de grippe", 
            "Faut-il se vacciner contre la grippe si on est malade", "La grippe peut-elle être traitée avec des remèdes maison", 
            "Que prendre en cas de fièvre avec la grippe", "Comment faire pour mieux dormir avec la grippe", 
            "Quels sont les médicaments en vente libre pour la grippe", "Combien de temps faut-il pour guérir de la grippe",
            "Quelles plantes médicinales aident à traiter la grippe", "Est-ce que boire beaucoup d'eau aide avec la grippe", 
            "Faut-il prendre des médicaments pour guérir de la grippe", "Quel est le traitement le plus efficace contre la grippe", 
            "Comment traiter la grippe naturellement", "Comment renforcer son immunité contre la grippe", 
            "Quels soins prodiguer à un enfant atteint de la grippe", "Est-ce que la grippe se guérit seule", 
            "Quels aliments sont à éviter en cas de grippe", "Comment éviter que la grippe ne s'aggrave", 
            "Quels sont les remèdes de grand-mère contre la grippe", "Dois-je consulter pour un traitement contre la grippe", 
            "La grippe se soigne-t-elle sans médicaments", "Quels remèdes maison peuvent soulager la grippe", 
            "Combien de jours dois-je rester au lit pour guérir de la grippe", "Quelles boissons sont conseillées pour la grippe", 
            "Comment diminuer la durée de la grippe", "Quels compléments alimentaires aident à lutter contre la grippe", 
            "Quel médicament en pharmacie est recommandé contre la grippe", "Quels soins prendre pour éviter les complications de la grippe", 
            "Est-ce que les inhalations peuvent aider avec la grippe", "Comment prévenir une rechute après une grippe", 
            "Quel traitement pour éviter que la grippe ne s'aggrave", "Est-ce que l'aspirine aide contre la grippe", 
            "Comment réduire les douleurs musculaires liées à la grippe", "Quel est le meilleur moyen de soigner la grippe"
        ],
        "response": "Reposez-vous, buvez beaucoup d'eau et consultez un médecin si nécessaire.",
        "next_intent": "exit"
    },
    {
        "intent": "ask_injury_cut",
        "examples": [
            "Je me suis coupé au doigt, que faire", "Comment stopper une coupure qui saigne", "je me suis coupé",
            "Ma coupure ne s'arrête pas de saigner, que dois-je faire", "Que faire en cas de coupure au bras",
            "J'ai une coupure légère, comment la soigner", "Coupure par objet tranchant, que faire", 
            "J'ai une plaie ouverte, comment la traiter", "Quels sont les premiers soins pour une coupure", 
            "Coupure avec un couteau, comment réagir", "Comment désinfecter une coupure", 
            "Ma coupure est rouge et gonflée, que faire", "Dois-je aller à l'hôpital pour une coupure profonde", 
            "J'ai une petite coupure, dois-je m'inquiéter", "Quelle est la meilleure façon de soigner une coupure", 
            "Faut-il utiliser de l'alcool pour nettoyer une coupure", "J'ai une coupure infectée, que faire", 
            "Quel produit utiliser pour désinfecter une coupure", "Dois-je consulter un médecin pour une coupure", 
            "Comment savoir si ma coupure est infectée", "Ma coupure saigne depuis longtemps, que faire", 
            "Comment protéger une coupure du contact avec l'eau", 
            "Quand dois-je changer le pansement d'une coupure", "Comment réduire la douleur d'une coupure", 
            "Que faire si la coupure est enflée", "Ma coupure fait mal, est-ce normal", 
            "Dois-je recoudre ma coupure si elle est profonde", "Que faire en cas de coupure sur un tendon", 
            "Ma coupure est sur mon visage, comment la soigner", "Comment éviter que ma coupure ne laisse une cicatrice",
            "Je me suis coupé en cuisinant, que dois-je faire", "J'ai une coupure profonde, dois-je m'inquiéter", 
            "Comment arrêter le saignement d'une coupure", "Dois-je utiliser un antiseptique sur ma coupure", 
            "J'ai une coupure sur le bras, que faire", "Comment traiter une coupure proprement", 
            "Ma coupure s'est infectée, que dois-je faire", "J'ai une coupure qui saigne beaucoup, que faire", 
            "J'ai une petite coupure, dois-je appliquer un pansement", "Ma coupure est sur ma main, que dois-je faire", 
            "J'ai une coupure au pied, comment la soigner", "Que faire si ma coupure ne guérit pas", 
            "Comment savoir si ma coupure nécessite des points de suture", "Ma coupure est douloureuse, que dois-je faire", 
            "J'ai une coupure qui saigne abondamment, dois-je consulter", "Ma coupure me fait mal, est-ce un signe d'infection", 
            "J'ai une coupure près d'une articulation, que faire", "Ma coupure s'est ouverte, que dois-je faire", 
            "J'ai une coupure profonde, dois-je aller à l'hôpital", "Comment éviter que ma coupure ne s'infecte", 
            "Ma coupure s'est enflée, est-ce normal", "Comment protéger une coupure pendant la guérison", 
            "Que faire en cas de coupure saignant abondamment", "Que faire pour une coupure qui ne guérit pas", 
            "Comment savoir si une coupure est grave", "J'ai une coupure profonde au bras, dois-je consulter un médecin", 
            "Dois-je mettre un pansement sur une petite coupure", "Comment traiter une coupure qui ne s'arrête pas de saigner", 
            "Comment soigner une coupure profonde sur le doigt", "Que faire en cas de coupure avec un couteau", 
            "Dois-je consulter pour une petite coupure", "J'ai une coupure au bras, dois-je consulter", 
            "Que faire en cas de coupure au bras avec saignement", "J'ai une coupure sur la jambe, comment la traiter", 
            "Comment traiter une coupure avec un couteau", "Comment désinfecter une coupure avec du savon", 
            "J'ai une coupure qui semble infectée, que faire", "Ma coupure est rouge et enflée, que dois-je faire"
        ],
        "response": "Nettoyez la coupure avec de l'eau et appliquez un pansement.",
        "next_intent": "confirm_sos_call"
    },
    {
        "intent": "ask_injury_fall",
        "examples": [
            "Je me suis fait mal en tombant, que faire", "Dois-je m'inquiéter après une chute", 
            "Je me suis blessé en tombant, dois-je aller à l'hôpital", "Que faire si je me suis fait mal en tombant", 
            "J'ai glissé et je suis tombé, que dois-je faire", "Dois-je consulter après une chute", 
            "Je me suis fait une entorse en tombant, que faire", "Je suis tombé, dois-je appeler les secours", 
            "Je me suis fait mal au dos en tombant", "Je me suis fait mal au poignet après une chute", 
            "Je me suis fait une bosse en tombant, que faire", "J'ai chuté, comment calmer la douleur", 
            "Que faire en cas de chute sur le genou", "Je me suis fait mal à la cheville après une chute", 
            "Comment soigner une blessure après une chute", "Je suis tombé dans les escaliers, que faire", 
            "Je suis tombé, comment réduire la douleur", "Je me suis cogné la tête en tombant, dois-je consulter", 
            "Je suis tombé de haut, que faire", "J'ai glissé et je suis tombé, est-ce grave ?", 
            "Je me suis tordu la cheville en tombant", 
            "Je me suis égratigné en tombant, comment désinfecter", "Je suis tombé sur le dos, dois-je m'inquiéter", 
            "Je me suis blessé à la jambe en tombant", "Dois-je consulter après une chute sur la tête", 
            "Je suis tombé en courant, dois-je m'inquiéter ?", "Je me suis fait mal au poignet en tombant, que faire", 
            "Je me suis fait une grosse bosse en tombant, dois-je m'inquiéter ?", "Je me suis tordu la cheville en glissant, que faire", 
            "Je me suis fait une entorse en tombant dans la rue, que faire", "Je me suis cogné la tête en tombant, dois-je aller à l'hôpital ?", 
            "Je suis tombé et je ressens une douleur à l'épaule, que faire", "Je me suis fait mal au poignet après une chute, que faire", 
            "J'ai glissé dans les escaliers, que dois-je faire ?", "Je me suis fait une entorse en tombant, dois-je consulter ?", 
            "Je me suis fait une bosse après une chute, dois-je consulter ?", "Je me suis fait mal en tombant dans les escaliers, que faire ?", 
            "Je suis tombé et je ressens une douleur au coude, dois-je consulter ?", "Je me suis fait mal à la hanche en tombant, que dois-je faire", 
            "Je me suis fait mal au bras en tombant, dois-je aller à l'hôpital ?", "Je me suis tordu la cheville en tombant, que dois-je faire ?", 
            "Je me suis fait mal en tombant sur le dos, que faire ?", "Je suis tombé et j'ai une douleur au dos, dois-je consulter ?", 
            "Je me suis blessé en tombant sur le poignet, que faire ?", "Je suis tombé en courant et j'ai mal au genou, que faire", 
            "Je me suis fait mal en tombant en vélo, que faire ?", "Je suis tombé en randonnée, que dois-je faire ?", 
            "Je me suis fait une entorse en descendant les escaliers, dois-je consulter ?", "Je me suis fait mal à la tête en tombant, dois-je consulter ?", 
            "Je suis tombé en vélo et je ressens une douleur au bras, que faire ?", "Je me suis blessé en tombant, dois-je aller à l'hôpital ?", 
            "Je me suis fait mal en courant, que faire ?", "Je suis tombé et j'ai une douleur au genou, dois-je appeler un médecin ?", 
            "Je suis tombé en randonnée et j'ai une douleur au genou, que faire ?", "Je suis tombé de mon vélo, dois-je appeler les urgences ?", 
            "Je me suis fait une bosse en tombant, dois-je appeler un médecin ?", "Je suis tombé en vélo, dois-je consulter ?", 
            "Je suis tombé sur le dos, dois-je appliquer de la glace ?", "Je suis tombé et j'ai une douleur au poignet, dois-je appeler un médecin ?", 
            "Je me suis cogné la tête en tombant, dois-je consulter ?", "Je suis tombé en vélo, dois-je consulter un médecin ?", 
            "Je me suis fait une entorse en jouant au football, que dois-je faire ?", "Je me suis blessé en tombant, dois-je consulter un médecin ?", 
            "Je me suis fait mal à la hanche en tombant, dois-je appeler un médecin ?", "Je suis tombé en courant, dois-je consulter ?", 
            "Je suis tombé en vélo, dois-je appeler un médecin ?", "Je me suis blessé à la cheville en tombant, dois-je appeler les secours ?", 
            "Je suis tombé de mon vélo et j'ai une douleur à la jambe, que faire ?"
        ],
        "response": "Si la douleur est intense, consultez un médecin. Sinon, reposez-vous et appliquez de la glace.",
        "next_intent": "confirm_sos_call"
    },
    {
        "intent": "confirm_sos_call",
        "examples": [
            "oui, appelle les secours", "je veux appeler les secours", "appelle les urgences", "oui",
            "contacte SOS immédiatement", "j'ai besoin d'un appel d'urgence", "je veux de l'aide, appelle SOS", 
            "appelle les secours s'il te plaît", "je veux que tu appelles SOS", "OK, appelle les urgences", 
            "oui, appelle une ambulance", "SOS, c'est urgent", "je veux appeler quelqu'un", 
            "appelle une aide médicale", "appelle les secours tout de suite", "je veux que tu appelles les secours", 
            "besoin d'une aide médicale", "contacte SOS pour moi", "j'ai besoin d'un appel SOS", 
            "OK, contacte les secours", "appelle une ambulance immédiatement", "s'il te plaît, appelle les urgences", 
            "oui, appelle les secours maintenant", "SOS immédiatement", "je veux que tu appelles une aide d'urgence", 
            "appelle immédiatement SOS", "contacte les urgences", "j'ai besoin que tu appelles une aide", 
            "SOS, appelle maintenant", "appelle pour moi", "appelle les secours maintenant"
        ],
        "response": "D'accord, j'appelle SOS. Veuillez rester calme.",
        "next_intent": None
    },
    {
        "intent": "decline_sos_call",
        "examples": [
            "non, ça ira", "je n'ai pas besoin d'appeler SOS", "ce n'est pas nécessaire d'appeler", 
            "je n'ai pas besoin d'aide", "pas besoin d'urgence", "je me sens bien, pas besoin de secours", 
            "ça va, pas d'appel SOS", "pas de SOS, merci", "tout va bien, pas besoin d'appeler", 
            "je vais bien, pas besoin d'intervention", "non, pas de besoin d'assistance", 
            "je vais bien, pas d'aide nécessaire", "tout est sous contrôle, pas besoin d'aide", 
            "pas nécessaire de contacter les secours", "pas d'appel d'urgence", "je n'ai pas besoin d'aide pour le moment", 
            "pas besoin d'aide, merci", "je suis OK, pas besoin de secours", "je vais bien, pas d'urgence", 
            "non, je n'ai pas besoin d'appel", "je peux gérer, pas besoin d'appeler SOS", 
            "pas besoin de contacter SOS", "je vais gérer, pas besoin de SOS", "pas d'urgence pour l'instant", 
            "non, pas besoin d'assistance immédiate", "je n'ai pas besoin d'appel urgent", 
            "ça ira, pas d'urgence", "tout va bien, pas d'appel nécessaire", "je suis en sécurité, pas besoin d'appeler", 
            "je peux m'en sortir sans appeler SOS"

        ],
        "response": "D'accord, prenez soin de vous. N'hésitez pas à appeler si besoin.",
        "next_intent": "exit"
    },
    {
        "intent": "unknown",
        "examples": [
            "je ne sais pas", "c'est pas clair", "je ne comprends pas", "je suis perdu", 
            "pardon", "peux-tu répéter", "rien de tout ça", "je ne suis pas sûr"
        ],
        "response": "Je n'ai pas compris, pouvez-vous reformuler ?",
        "next_intent": None
    }
]

# Génération des phrases d'entraînement
train_sentences = [example for intent in training_data for example in intent['examples']]
train_labels = [intent['intent'] for intent in training_data for _ in intent['examples']]

# Vérification pour les phrases ambigües ou répétitives
for i, sentence in enumerate(train_sentences):
    if train_sentences.count(sentence) > 1:
        print(f"Phrase répétée ou ambigüe détectée : {sentence} pour l'intention '{train_labels[i]}'")
